name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git
        run: |
          git config --global user.email "vibhor.aggarwal1601@gmail.com"
          git config --global user.name "Vibhoragg16"

      - name: Authenticate and Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://user:$HF_TOKEN@huggingface.co/spaces/vibhoragg/Math_Problem_Solver
          git add .
          git commit -m "Sync to Hugging Face Hub" || echo "No changes to commit"
          git push origin main
